apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
  labels:
    app: nextjs-app
spec:
  replicas: 2 # Requirement: with replicas
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      # NOTE: For deployment with MINIKUBE DOCKER-ENV TRICK, 
      # imagePullSecrets are REMOVED and imagePullPolicy is set to Never.
      containers:
      - name: nextjs-app-container
        image: nextjs-app:local      # ⬅️ Must match the image built in Minikube's Docker daemon
        imagePullPolicy: Never       # ⬅️ IMPORTANT for Minikube local-build trick
        ports:
        - containerPort: 3000
        # Requirement: Health Check (Readiness Probe)
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"