apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-devops-deployment
  labels:
    app: nextjs-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-devops
  template:
    metadata:
      labels:
        app: nextjs-devops
    spec:
      # Authentication for private GHCR image pull
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: nextjs-container
          # IMPORTANT: Ensure this image path is correct and ALL lowercase
          image: ghcr.io/vibudhan/devops_assessment-2:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
