apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-devops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-devops
  template:
    metadata:
      labels:
        app: nextjs-devops
    spec:
      containers:
        - name: nextjs-container
          image: ghcr.io/vibudhan/devops-assessment-2:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

