apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  type: NodePort # Use NodePort to easily access the app in Minikube
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 3000 # Container port (Next.js default)
      nodePort: 30081 # Port to access on Minikube VM (30000-32767 range)