apiVersion: v1
kind: Service
metadata:
  name: nextjs-devops-service
  labels:
    app: nextjs-devops
spec:
  type: NodePort
  selector:
    app: nextjs-devops
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
